"""empty message

Revision ID: 37167eb39ad8
Revises: 
Create Date: 2023-04-02 23:10:30.417927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37167eb39ad8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('avatar',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('avatar',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
