"""empty message

Revision ID: 792178562901
Revises: 37167eb39ad8
Create Date: 2023-04-02 23:18:20.009621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '792178562901'
down_revision = '37167eb39ad8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('avatar',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('avatar',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
